# Generated by Django 2.0.6 on 2018-06-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.User'),
        ),
    ]
