# Generated by Django 2.0.6 on 2018-06-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_user_block_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='block_users',
        ),
        migrations.AddField(
            model_name='user',
            name='block_users',
            field=models.ManyToManyField(to='models.User'),
        ),
    ]
