# Generated by Django 2.0.6 on 2018-06-19 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_relations',
            new_name='user',
        ),
    ]
